### PR TITLE
11557 - Homepage updates

### LINKED ISSUE #11557: Website Redesign - Homepage V3
### User story
As a User,
I want to visit the ReportStream Homepage,
So that I can become informed about ReportStream

### Designs
- Figma Link https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3824%3A4993&mode=design&t=EVSonRhGjbiURooL-1

### Verification Steps
    - Code Review
    - Trial / Dev environment signoff by Product / Design
    - Staging environment signoff by Product / Design / Stakeholders (Need to be explicit)
    - Production environment signoff by Engineering, Product and Design

### Acceptance Criteria:
- [ ] Storybook update required
- [ ] Manual Testing Steps

**New additions to current version**
- [x] Add 'What is ReportStream compatible with?' blurb, adjust to two-column layout next to 'Accepted data types and conditions'

**Design changes from current version**
- [x] Add text below 'Public health entities': "ReportStream helps state, local, and territorial agencies across the United States get the data they need for the best possible public health responses."
- [x] Add 'Health care organizations, facilities, and labs' section
- [x] Change button copy from 'See all partners' to 'See full network'

### Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=3824%3A4993&mode=design&t=EVSonRhGjbiURooL-1

### Additional Details:
TBD

### PR DESCRIPTION
**Pull request by penny-lischer**
This PR ...

Website Redesign - Homepage V3

Test Steps:
1. Log into RS
2. See changes

## Changes
- Additions per Figma
Screenshot 2023-10-13 at 12 29 18 PM
Screenshot 2023-10-13 at 12 29 26 PM

### Testing
- [x] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #11557

### CODE REVIEW

**Comment by audreykwr** [comment]
Thanks, @penny-lischer! 

- [ ] It looks like "See our full network" is linking to the old where we're live page and not the new "our network" page.

**Review by jpandersen87 — APPROVED** [review]

**Review by jakefishbein-navapbc — CHANGES_REQUESTED** [review]
Screen Shot 2023-10-16 at 3 48 00 PM
@penny-lischer I added some screenshots pointing out discrepancies with the Figma file. Please let me know if you have questions. Thanks.

CC: @jillian-hammer 

Screen Shot 2023-10-16 at 3 56 02 PM

**Comment by audreykwr** [comment]
@jakefishbein-navapbc the external link icon is added automatically to external links and is a CDC requirement. so that's fine. We just don't add it to Figma because the code automatically does it for us so eng doesn't need to do that

**Comment by penny-lischer** [comment]
> Screen Shot 2023-10-16 at 3 48 00 PM @penny-lischer I added some screenshots pointing out discrepancies with the Figma file. Please let me know if you have questions. Thanks.
> CC: @jillian-hammer
> 
> Screen Shot 2023-10-16 at 3 56 02 PM

@jakefishbein-navapbc the body is 1.06rem which is the same size as listed under the Public health entities. The figma and our fonts are not always one-one. @jillian-hammer please advise.

**Review by etanb — APPROVED** [review]

**Pull request merged**
