### PR TITLE
Turn Palo Alto on for production

### PR DESCRIPTION
**Pull request by cwinters-usds**
This PR flips the switch to enable the Palo Alto in production. (A retry from https://github.com/CDCgov/prime-reportstream/pull/2828)

## Deployment Checklist

- [ ] Ensure changes to CDC DNS are applied (Richard Teasley should notify us)
- [ ] Notify senders of downtime - Anshul
- [ ] Disable the release GitHub Action - Chris
- [ ] Merge this PR - Chris
- [ ] Deploy Terraform to production - Chris
    - [ ] Deploy `tf-01-network` to production
    - [ ] Deploy `tf-02-config` to production
    - [ ] Deploy `tf-03-persistent` to production
    - [ ] Deploy `tf-04-app` to production
- [ ] Verify we have App Insights logs - Jim
- [ ] Verify we have no blocked SFTP connection to senders - Jim
- [ ] Inspect Palo Alto logs to see if any unexpected traffic is blocked - Timothy
- [ ] Perform post-deployment validations - Jim
- [ ] Enable the release GitHub Action - Chris
- [ ] Notify receivers they can remove our old IP address from their firewall - Ming/Adrian

### CODE REVIEW

**Comment by ronaldheft-usds** [comment]
@cwinters-usds Thanks for updating the checklist! These steps are no longer needed:

> - [ ] Update the dnsmasq mapping file for production IP addresses - Chris
>   - [ ] Submit a PR with the changes
>   - [ ] Apply tf-01-network to force the dnsmasq server to update

**Comment by cwinters-usds** [comment]
@ronaldheft-usds thanks much for the pointer, fixed

**Review by ronaldheft-usds — CHANGES_REQUESTED** [review]
I think we also need a step to change the DNS for the function app to `172.17.0.135`. It's the `WEBSITE_DNS_SERVER` environment variable in the Terraform. That can be set ahead of time for this PR.

**Comment by cwinters-usds** [comment]
@ronaldheft-usds good point -- I forgot to add that after bringing it up in our standup!

Is there any reason not to make this change [in the terraform here](https://github.com/CDCgov/prime-reportstream/blob/master/operations/app/src/modules/function_app/main.tf#L26)? It'd get applied in the 'Deploy Terraform to Production' step and the function app would be restarted as a result.

**Comment by ronaldheft-usds** [comment]
> @ronaldheft-usds good point -- I forgot to add that after bringing it up in our standup!
> 
> Is there any reason not to make this change [in the terraform here](https://github.com/CDCgov/prime-reportstream/blob/master/operations/app/src/modules/function_app/main.tf#L26)? It'd get applied in the 'Deploy Terraform to Production' step and the function app would be restarted as a result.

Nope! That's the perfect spot! I would add it to this PR, so when we merge, that change will be included.

**Comment by cwinters-usds** [comment]
@ronaldheft-usds added that config item, also a short doc about DNS -- hopefully it makes sense.

**Pull request merged**
