### PR TITLE
Create E2E tests for api page

### LINKED ISSUE #14782: Create E2E tests for the API Guide Page
## Problem statement
This page on the RS website needs End-to-end (E2E) tests created to ensure that it works properly before merging into master. Without E2E tests, some features/links may not function/load properly and we wouldn't know until a user tried to use them.

The Page is located at: https://reportstream.cdc.gov/developer-resources/api

## What you need to know
- This is based off the investigation from #11307
- [E2E Test Creation Tracker](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B6EB440E8-4A08-4F4F-A2C1-ED7BB23E665B%7D&file=E2E%20Test%20Tracker.xlsx&action=default&mobileredirect=true&wdsle=0)
- Strategy discussed for checking content load: check to see if every DIV on this page loaded

## Acceptance Criteria
As any user, logged in or not, check that:
- [ ] The page loads
- [ ] If there is an error, the error is shown on the page
- [ ] Page content loads without errors (including if the footer is showing, but not its functionality) (also, not checking the content itself, but just if it loads)
- [ ] Components work as expected (eg, accordion expands/collapses, side nav, etc)

### PR DESCRIPTION
**Pull request by jpandersen87**
Fixes #14782

This PR adds E2E tests for the api page.

### CODE REVIEW

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by etanb — CHANGES_REQUESTED** [review]
we should be using the new `.testHeader()` and `.testFooter()` methods available in `BasePage` instead of repeating the logic for header / footer in these e2e tests.

We also have logic for `.testSidenav()`: https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/e2e/pages/BasePage.ts#L150-L159

**Comment by jpandersen87** [comment]
> we should be using the new `.testHeader()` and `.testFooter()` methods available in `BasePage` instead of repeating the logic for header / footer in these e2e tests.
> 
> We also have logic for `.testSidenav()`: https://github.com/CDCgov/prime-reportstream/blob/master/frontend-react/e2e/pages/BasePage.ts#L150-L159

fixed

**Review by etanb — APPROVED** [review]

**Pull request merged**
