### PR TITLE
Fixed MO Validation Error ORC-2 and OBR-2 by replacing the value give…

### PR DESCRIPTION
**Pull request by oslynn**
This PR fixed ORC-2 and OBR-2 with the value given by receiver MO

Test Steps:
1. ./gradlew clean package
2. ./prime data --input junk/MO/From/2022-08-05/prescryptive.default/2022080510371503_prescryptive-covid-19-4643ca5b-d13e-44b3-9826-014728d8e892-20220804173602.hl7 --input-schema HL7/prescryptive-covid-19 --output-dir junk/output --route

Result: 
ORC-2:  Placer Order Number:                        
  ORC-2-2:                                          RX MART PHARMACY
  ORC-2-3:                                          RX MART PHARMACY
  ORC-2-4:                                          CLIA

OBR-2:  Placer Order Number:                           
  OBR-2-2:                                             RX MART PHARMACY
  OBR-2-3:                                             RX MART PHARMACY
  OBR-2-4:                                             CLIA

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6215

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

**Comment by oslynn** [comment]
After the PR is approved, I need to email Prescryptive to include the PID-3.5- PATIENT_RESULT[0].PATIENT.PID.PatientIdentifierList[0].IdentifierTypeCode in the message (MSH-10: ) and resend it.  We have fixed the ORC-2 and OBR-2 on RS already.

**Review by jorg3lopez — APPROVED** [review]
Nicely done, Ott

**Review by GilmoreA6 — COMMENTED** [review]
Hi Ott, What this is doing is defaulting "RX MART PHARMACY^RX MART PHARMACY^CLIA" into ORC-2 and OBR-2 for every messages going to MO regardless of source which I don't believe is accurate. I think we want to back out these changes and ask the Prescryptive sender to populate those fields on the inbound message.

**Comment by oslynn** [comment]
@GilmoreA6 MO was asking for ORC-2 and OBR-2 to be filled with "RX MART PHARMACY^RX MART PHARMACY^CLIA".  However, I agree with you.  Should we just ask Prescryptive to fill the value for these fields?

**Pull request merged**
