### PR TITLE
Added test_type element to senders schemas that baseOn covid-19

### PR DESCRIPTION
**Pull request by oslynn**
This PR adds test_type element to all sender's schemas that baseOn covid-19 schema.

Test Steps:
1. ./gradlew clean package
2. ./prime test

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7480

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

**Review by jimduff-usds — COMMENTED** [review]
I don't understand the context here.    So, a new column was added to the LIVD table, called test_type.    

- What's it for?  
- What are some typical values for test_type?
- Is the intention to pass that value on to receivers?  Where does it appear in HL7 data?
- And for receivers getting CSVs (like HHSProtect), is the intention to add a new column?   If so, why?   Has HHSProtect asked for that?   Are we planning to tell them its coming?

@jimduff-usds thank you for reviewing the PR.
.  Yes, a new column (column Z: TestType) was added to the LIVD-SARS-CoV-2-2022-10-19.xlxs LOINC Mapping Table.
. It is for indicating the Type of Test.
. Currently, we use the column to check for Test Type.  Latest, we use to filter out the Negative Antigen Test Type for CO since CO no longer needs us to report the Negative Antigen Test to them.
. There is no field in HL7 for the Test Type.  It only lives on LIVD Table.
. Currently, there is no Receivers getting CSV need to add the new column.
.  HHSProtect doesn't ask for the field.  Only CO that asked us to filter out the Negative Antigen Test.

Here is column:
image

**Comment by jimduff-usds** [comment]
OK, so the new column has the values “Mol” and “Antigen”.   The use case is that CO wants to filter out negative Antigen tests from all senders.  To make that happen, we have to have a column available with test_type, so we can filter on it.

Did we really have to add the column to all those outgoing receiver-facing schemas?   Would it have been sufficient to add it to incoming (sender) schemas only?   I may be wrong but my understanding is that _filtering occurs on our internal format, prior to creating the outgoing format,_ true?   So adding the value to outgoing schemas does not do anything.   Does that sound right?

**Comment by jimduff-usds** [comment]
I think AZ and Strac are both receiver schemas.  Maybe AZ-IHS too?   Check with @mauricereeves

**Review by MauriceReeves-usds — APPROVED** [review]
Based on your responses to @jimduff-usds's questions, and the tests passing, I'm approving the PR. Thank you for addressing this.

**Review by brick-green — APPROVED** [review]

**Pull request merged**
