### PR TITLE
added the new valueset, still need to implement tests

### PR DESCRIPTION
**Pull request by pablocaviglia**
This PR adds the following valueset to covid-19

    **- code: 373121007
      display: Test not done**

## Changes
- covid-19.valuesets

### Testing
- [x] Tested locally?
- [x] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Security
- [ ] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

### Process
- [ ] Includes a summary of what a code reviewer should verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
*List GitHub issues this PR fixes*
- #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

### CODE REVIEW

**Review by RickHawesUSDS — CHANGES_REQUESTED** [review]
This is tricky value set. Notice the comment to add values to obx8 mapper when added here. Yikes. Looking at the mapper, I see that many other people haven't added cases to the mapper. I'll take care of them in my PR. Could you add the 373121007 case to the mapper in this PR?

**Comment by pablocaviglia-baires** [comment]
> This is tricky value set. Notice the comment to add values to obx8 mapper when added here. Yikes. Looking at the mapper, I see that many other people haven't added cases to the mapper. I'll take care of them in my PR. Could you add the 373121007 case to the mapper in this PR?

@RickHawesUSDS @jimduff-usds, what value should I use for that code? N or A ?

image

**Comment by jimduff-usds** [comment]
Pablo, it looks like the only choices are A for Positive, or N?    Its certainly not positive, so it has to be N then.

**Comment by pablocaviglia-baires** [comment]
> Pablo, it looks like the only choices are A for Positive, or N? Its certainly not positive, so it has to be N then.

fixed

**Review by jimduff-usds — APPROVED** [review]
LGTM.

**Pull request merged**
