### PR TITLE
Experience/14140/dap fix

### LINKED ISSUE #14140: Whitelist the DAP tag for ReportStream website analytics
## Problem statement
The DAP code (used to track our public website analytics through Google Analytics) is being blocked by our agency Content Security Policy. We need to whitelist the DAP code so the tag is allowed to send data.

## What you need to know

- 

## Acceptance criteria

- [ ] DAP code is no longer being blocked by our Content Security Policy
- [ ] Check (with Chris) that GA4 is working properly (collecting data from ReportStream website)

### PR DESCRIPTION
**Pull request by etanb**
Adds `https://www.google-analytics.com` and `https://www.googletagmanager.com` to our CSP.

Fixes #14140

### CODE REVIEW

**Review by jpandersen87 — CHANGES_REQUESTED** [review]
This only updates the local-web server based CSP. Devops will need to fix the CSP header in azure.

**Comment by etanb** [comment]
> This only updates the local-web server based CSP. Devops will need to fix the CSP header in azure.

@jpandersen87 I've pinged Devops in their Slack channel. Let me know if that's sufficient. I still think we should merge this for posterity?

**Comment by etanb** [comment]
## For Devops:

**Context:**

> CALL TO ACTION: If your agency self-hosts the DAP code on your own servers, you must ensure that you are using the latest version of the DAP code, which can be found in the DAP [Github repo](https://github.com/digital-analytics-program/gov-wide-code) along with capabilities documentation, release notes, and implementation instructions).
If your agency websites are using our centrally-hosted DAP tag via https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js, no action is required. We strongly encourage agencies to use our [centrally-hosted DAP tag](http://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js) to help your websites benefit from the seamless DAP code updates.

**Problem:**

With this new tag we added to our site, the sites are currently being blocked by our CSP:

image

**Solution:**

Add the following to our CSP: 

- `https://www.google-analytics.com`
- `https://www.googletagmanager.com`

**Review by penny-lischer — APPROVED** [review]
lgtm

**Review by jpandersen87 — APPROVED** [review]
approving now that the devops portion is underway in another issue

**Pull request merged**
