### PR TITLE
15059 - added github action workflow for frontend smoke tests to be run against live data

### LINKED ISSUE #15059: Create reusable github action to run smoke tests on deployment
## Problem statement

We would like to run smoke tests before deployment to production to ensure that our application is functioning as intended.

## What you need to know

Spike for smoke tests [here](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14210)

## Acceptance criteria

- [ ] Create a github action for user to run once the backend and frontend checks have completed. Action will trigger the following
`yarn run test:e2e-smoke`

## To do

- [ ] ...

### PR DESCRIPTION
**Pull request by penny-lischer**
This PR ...

Added github action workflow for frontend smoke tests to be run against live data.

Test Steps:
1. Run the `Start Frontend Smoke Tests` workflow.
You should be prompted to select your admin un/pw for such environment.

## Changes
- 

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #15059

### CODE REVIEW

**Review by victor-chaparro — APPROVED** [review]

**Comment by etanb** [comment]
@penny-lischer when should this test be run?

**Comment by snesm** [comment]
> @penny-lischer when should this test be run? unless i'm missing something, i don't see a trigger for this Github action?

@etanb  `workflow_dispatch:` is a "run manually" trigger.

**Comment by etanb** [comment]
@snesm so the idea here is that whoever is on deployment duty will have to run this manually? would it be worth figuring out an automated trigger, ie pushing to a specific branch like `deployment`?

**Review by jeremy-page — APPROVED** [review]
LGTM!

**Comment by snesm** [comment]
> @snesm so the idea here is that whoever is on deployment duty will have to run this manually? would it be worth figuring out an automated trigger, ie pushing to a specific branch like `deployment`?

@etanb after a few manual runs to prove that this works properly, fully automating may be desirable.

**Pull request merged**
