### PR TITLE
Updates LIVD csv file

### PR DESCRIPTION
**Pull request by jorg3lopez**
This PR updates the LIVD table by updating the LIVD csv file.

## Changes
- Uploaded new csv file: LIVD-SARS-CoV-2-2021-08-11.csv to replace  LIVD-SARS-CoV-2-2021-04-28.csv
- Checked LIVD-Supplemental-2021-06-07.csv file against the newly uploaded LIVD-SARS file for possible name changes of tests
-  Changes related to running generatedocs command

## Checklist
- Unit test passed
- integration test passed
- end to end test passed
-  quick-test all test passed
### Testing
- [x ] Tested locally?
- [ ] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

## Fixes
*List GitHub issues this PR fixes*
- #1991

### CODE REVIEW

**Review by MauriceReeves-usds — APPROVED** [review]
lgtm. I'd like @RickHawesUSDS to verify as well.

**Comment by MauriceReeves-usds** [comment]
@jorg3lopez it looks good to me from an eyeball perspective, but I would like @RickHawesUSDS to take a look as well since this is a very important piece of our mapping. Also, when you did your local testing, what testing did you use? Did you do a full integration test and run `end2end`?

**Comment by jorg3lopez** [comment]
> @jorg3lopez it looks good to me from an eyeball perspective, but I would like @RickHawesUSDS to take a look as well since this is a very important piece of our mapping. Also, when you did your local testing, what testing did you use? Did you do a full integration test and run `end2end`?

I did build and then ran testEnd2End. Just did that again a few moments ago, to verify.

**Comment by RickHawesUSDS** [comment]
@jorg3lopez Please describe the testing you did on this change.

**Comment by jorg3lopez** [comment]
> @jorg3lopez Please describe the testing you did on this change.

@RickHawesUSDS These are the tests I ran: gradle test, gradle testIntegration, gradle testEnd2End, and I also did a built which ran all the tasks; everything passed.

**Comment by RickHawesUSDS** [comment]
@jorg3lopez Did you run  `quicktest all`?

**Comment by jorg3lopez** [comment]
> @jorg3lopez Did you run `quicktest all`?

@RickHawesUSDS I just did it, everything passed.

**Comment by jorg3lopez** [comment]
@RickHawesUSDS Let me run it again, I want to make sure of it. (./quick-test all)

**Review by RickHawesUSDS — APPROVED** [review]

**Pull request merged**
