### PR TITLE
Update Jest to run in UTC

### PR DESCRIPTION
**Pull request by stephenkao**
This changeset updates our test commands to run in UTC all the time.  This was causing inconsistencies between our machines because timezones are anathema to tests.

### CODE REVIEW

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by etanb — APPROVED** [review]
LGTM! Is there a place we could document this?

**Review by jpandersen87 — APPROVED** [review]
yep, the test passes now. bitten by the datetime programmer's curse

**Comment by stephenkao** [comment]
> LGTM! Is there a place we could document this?

@etanb Sure, where are you thinking the documentation should live?  I personally think having these sorts of environment variables in package.json/Jest config makes our global values clear (and hopefully prevents anyone from having to think about timezones while writing tests), but not problem to call attention to it just in case.  I could add it to the forthcoming test conventions doc if you'd like!

I've also used the simple-but-effective [MockDate](https://github.com/boblauer/MockDate) for things like Storybook, and that's something we could consider using as well.

**Pull request merged**
