### PR TITLE
change `npm` to `yarn` for build_frontend_react's package management

### PR DESCRIPTION
**Pull request by TomNUSDS**
We still want to lock npm at version 14, but use the yarn package manager.

See SimpleReport's frontend github action as a reference:
https://github.com/CDCgov/prime-simplereport/blob/main/.github/actions/build-frontend/action.yml

Related change: https://github.com/CDCgov/prime-reportstream/pull/2386

### CODE REVIEW

**Comment by TomNUSDS** [comment]
@sean-usds @kevinhaube FYI

**Review by sean-usds — APPROVED** [review]
lgtm! 🧶

**Comment by TomNUSDS** [comment]
OK. I updated the `release.yml` section for the react app even though I don't think it's being used for the release yet.

@ronaldheft-usds Recently, Github actions added support for calling other actions by reference to reduce duplication.
https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

**Review by kevinhaube — APPROVED** [review]
Nice :+1:

**Review by ronaldheft-usds — APPROVED** [review]
Looks great!

We are actually deploying the react app to staging, so good call in updating the `release.yml` workflow.

Thanks for also pointing out the recently released ability to de-duplicate code in GitHub Actions. Our release workflow definitely needs it! Tracking it as https://github.com/CDCgov/prime-reportstream/issues/2011

**Pull request merged**
