### PR TITLE
8598 update CA Jurisdictional filter

### PR DESCRIPTION
**Pull request by jalbinson**
This PR shows what settings changes are needed to update the jurisdictional filter for the California DPH. The original filter would route results to California if the testing company happened to be based in California even if the patient was located in another state and was tested there.

Test Steps:
1. Load these settings into your local repo (removing the transport section)
2. Send test data where the `ordering_facility_state` is `CA` but the `ordering_provider_state` is not.
3. Ensure data is not routed to CA

## Changes
- jurisdictional filter for CA-DPH

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- 8598

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

**Comment by jalbinson** [comment]
> What does CA want to to happen when ordering facility state = CA, Patient State <> CA, and Provider State is blank? With the proposed filters those results will also be filtered

According to the ticket, they only want data if a patient is from California or if they were seen in by a provider in California. In your scenario we would not send that result to CA.

**Comment by brick-green** [comment]
> > What does CA want to to happen when ordering facility state = CA, Patient State <> CA, and Provider State is blank? With the proposed filters those results will also be filtered
> 
> According to the ticket, they only want data if a patient's address is in California or if they were seen by a provider in California. In your scenario we would not send that result to CA.

I would consider asking CA if that's their intended behavior. I think it's possible they just didn't consider that possibility. There's a lot of power in the filters so I get nervous when we get close to making assumptions with them. Better to be safe than sorry.

**Comment by jalbinson** [comment]
Clarifying email sent directly to contacts at the California DPH.

**Comment by jalbinson** [comment]
California no longer needs this.

**Pull request closed without merging**
