### PR TITLE
Fixes authorization bug for `/settings/receivers` list API endpoint

### PR DESCRIPTION
**Pull request by kevinhaube**
This PR fixes a bug that directed auth to look for `DH` rather than `DHmd_phd`

Test Steps:
1. Ensure your OktaPreview account has only a receiver org present in its groups, no `DHPrimeAdmins`
2. Make a call with that bearer token to the `settings/organizations/{organizationName}/receivers` endpoint
3. Ensure you're authorized to access receivers for that organization.
4. Ensure you're NOT authorized to access other org's receivers.

## Changes
-  Plugs a variable into the auth function

### Testing
- [X] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
No
- Does this PR include changes in authentication and/or authorization of existing endpoints?
> **Yes**, it removes an empty string and replaces it with the org name, so the auth process looks for the proper Okta group claim.
- Does this change introduce new dependencies that need vetting?
No
- Does this change require changes to our infrastructure?
No
- Does logging contain sensitive data?
No
- Does this PR include or remove any sensitive information itself?
No

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

**Review by TomNUSDS — COMMENTED** [review]
There are 3x cases of `oktaAuthentication.checkAccess(request, "")` in the settings file.

Should this fix be made in all 3 locations?

**Comment by kevinhaube** [comment]
> There are 3x cases of `oktaAuthentication.checkAccess(request, "")` in this Settings file.
> 
> Should this fix be made in all 3 locations?

Unsure, but the logic holds that they'd be bugged in the same way -- I can add those in if it makes sense

**Review by TomNUSDS — COMMENTED** [review]
Another thought: should Setting's `oktaAuthentication` ONLY allow Prime Admins to call it?

**Comment by kevinhaube** [comment]
> Another thought: should Setting's `oktaAuthentication` ONLY allow Prime Admins to call it?

We use settings GETs everywhere on the front-end but admins are the only ones changing any of those values in the settings editor, and should probably only allow for admin access (i.e. PUT, DELETE)

**Review by clediggins-usds — APPROVED** [review]

**Pull request merged**
