### PR TITLE
13796: record time for decoding FHIR bundles

### PR DESCRIPTION
**Pull request by mkalish**
This PR adds some logging on how long decoding the ndjson into FHIR bundles take

Test Steps:
n/a

## Changes
- Records how many lines of ndjson and how long it took to decode them into FHIR bundles

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- #13796 

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

### CODE REVIEW

**Review by jalbinson — APPROVED** [review]
Another way to do this is use
```kotlin
val elapsed = measureTimeMillis {
  // your code            
}
```

Either approach is fine with me.

**Comment by jalbinson** [comment]
I just watched this and now think your approach is better 😄 

https://youtu.be/i1wysckHg2o

**Comment by jalbinson** [comment]
Looks like the way to do it with the Kotlin time library (with a Monotonic clock) is:

```kotlin
val elapsed = measureTime {
  // your code
}

val millis = elapsed.inWholeMilliseconds
```

Or you can just offload the calculation to the library.
```kotlin
val now = TimeSource.Monotonic.markNow()
// your code
val elapsedMillis = now.elapsedNow().inWholeMilliseconds
```

Or you can just leave it as is. It was interesting to look into.

**Comment by mkalish** [comment]
Oh that's better,  I re-used this logic from another spot, but I think when I implemented it then the timing API was still experimental and not finished.  I'll switch it out

**Review by arnejduranovic — APPROVED** [review]

**Pull request merged**
