### PR TITLE
Update prime-router docs to reference main branch

### PR DESCRIPTION
**Pull request by jack-h-wang**
This PR updates document references to the `main` branch (previously `master`).

## Changes
- Change references of `master` to `main`.

### CODE REVIEW

**Review by emvaldes — COMMENTED** [review]
I can see there are changes to these documents that extend beyond the simple replacement of master to main.
I am deeply sorry but I cannot approve these changes because I do not have the expertise on the components that are directly related to the development side of the house.
The changes in overall seem right but someone else will need to approve them.

**Review by arnejduranovic — APPROVED** [review]

**Comment by jack-h-wang** [comment]
@emvaldes approval from the development side was already given by @arnejduranovic. There are no functional changes, only updates to text and links. We need an approval from DevOps to be able to merge.

**Review by scott-aquia — APPROVED** [review]

**Review by emvaldes — APPROVED** [review]
I am rubber stamping these changes based on the approval made by the development team and the scope they have defined for these changes.

**Comment by emvaldes** [comment]
I am wondering if this is caused by something related to the migration from master to main branch.
Maybe there is some active reference to the legacy master branch that is stalling these processes to be completed.

**Comment by emvaldes** [comment]
It's puzzling to see that nothing changed infrastructure wise and yet a build was trying to be ran for hours and suddenly worked. This is something we need to investigate.

**Pull request merged**
