### PR TITLE
Okta Migration Changes

### PR DESCRIPTION
**Pull request by jpandersen87**
This PR encapsulates all of the changes needed for the Okta migration from various tickets.

NOTE: The .TF changes shall be part of another PR, this is just backend and front end application code. Once TF changes are pushed to master, this branch can be updated and deployed to a test environment for verification prior to merging to master.

Deployment Plan: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Engineering/Okta%20Deployment%20Plan.docx?d=w53a859ef71e242d8888e560604a6c6b5&csf=1&web=1&e=uu9n60

### CODE REVIEW

**Comment by jpandersen87** [comment]
@jeremy-page @snesm branch now only consists of the URL/ClientID changes for migration

**Comment by jeremy-page** [comment]
Need to figure out the conflicts first, should be done today.

**Comment by supriyaaddagada** [comment]
operations\app\terraform\modules\function_app\main.tf has been updated to read the cors settings from locals file, please update the CORS settings in below file

operations\app\terraform\modules\function_app\locals.tf

**Review by snesm — CHANGES_REQUESTED** [review]
@jpandersen87 operations\app\terraform\modules\function_app\main.tf has been updated to read the CORS settings, sticky_slot_implicit_settings_names from locals file, please update the CORS settings and sticky_slot_implicit_settings_names in below file

operations\app\terraform\modules\function_app\locals.tf

**Comment by jeremy-page** [comment]
Please do not merge this until we have a plan how to apply...once it's in the pipeline we're going through with it!

**Review by arnejduranovic — APPROVED** [review]

**Pull request merged**
