### PR TITLE
Website Redesign - Our Network

### LINKED ISSUE #11134: Website Redesign - Our Network
As a User,
I want to visit the Our Network Page,
So that I can become informed about ReportStream's network of organizations

### Designs
- Figma Link https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=925%3A4974&mode=design&t=JFcMNWQHEGLr4HrU-1

### Content Updates
-  Content Links TBD
  
### Analytics
- Page Load
- Button / Link clicks

### Verification Steps
- Code Review
- Trail / Dev environment signoff by Product / Design
- Staging environment signoff by Product / Design / Stakeholders 
- Production environment signoff by Engineering, Product and Design

### Acceptance Criteria:
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps
- [ ] Add to Navigation

### Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=925%3A4974&mode=design&t=JFcMNWQHEGLr4HrU-1

### Additional Details
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages.

### PR DESCRIPTION
**Pull request by jpandersen87**
Fixes #11134

This PR implements the redesigned our network page.

### CODE REVIEW

**Review by penny-lischer — APPROVED** [review]
LGTM

**Comment by yudonoodles** [comment]
Yay, this page came together nicely spacing wise :) 

**Design notes:**
- [ ] Add center aligned **Connected** and **Not Connected** legend on the bottom of the usa-map. See on [homepage](https://pdhstagingpublictrial01.z13.web.core.windows.net/) 
- [ ] Left align the caption "Heitordp, CC0, via Wikimedia Commons"
- [ ] Adjust list items so that they are aligned for both STLTs and Senders (see Figma design)
Screenshot 2023-09-11 at 12 52 46 PM
Screenshot 2023-09-11 at 12 52 55 PM

**Comment by yudonoodles** [comment]
- [ ] Standardize the padding on the legend to margin-top-2 (from here on)
- [ ] Can we remove margin-left and margin-right values on usa-map? Is there a reason why you think we should keep it?

**Review by audreykwr — APPROVED** [review]

**Review by yudonoodles — APPROVED** [review]
All updates look good - thanks Joseph!

**Pull request merged**
