### PR TITLE
Website Redesign - Getting started

### LINKED ISSUE #10908: Website Redesign - Getting started
As a User,
I want to visit the ReportStream **Getting Started** Page,
So that I can become informed about ReportStream and find more information on how to get started.

Designs
- Figma Link: https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design
Content Updates
- [See Figma Link](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design)
Page Title
- "CDC ReportStream - Getting Started"
Analytics
- All links
- Page Load
Storybook updates
- TBD
Verification Steps
- Signed off in Staging by Product / Design
- Signed off in Production by Product / Design / Engineering

Acceptance Criteria:
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps

Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design
- Platform API Endpoints - N/A
- Links - TBD

Additional Details:
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages.

### PR DESCRIPTION
**Pull request by jpandersen87**
Fixes #10908

This PR implements the getting-started page.

### CODE REVIEW

**Review by etanb — APPROVED** [review]

**Comment by audreykwr** [comment]
- [ ] The link for "Learn more" under get started as a healthcare organization is not linked to the page
- [ ] This is my bad not yours, but can we change the colon to a period in "These are the current data types we accept and the growing list of conditions that ReportStream can help you send or receive:"

**Comment by yudonoodles** [comment]
On 05/15/23, we decided to use desktop-lg for public site which means max width is 1200 px. Design is based on desktop-lg max-width.  Please update the following:
- [ ] Update max-width from 87.5rem to 75rem/1200 px
- [ ] Use H3 for usa card header instead of the H2
- [ ] Add margin-top to rs-tile group: 42px
- [ ] Add margin-top to p tag: 20px (this may have already been adjusted) 

The list of updates assumes that the spacing updates made on [Get started sending data](https://github.com/CDCgov/prime-reportstream/pull/11020) have been inherited here also, so I have not added all the spacing notes.

**Review by KeithNava — APPROVED** [review]

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by yudonoodles — APPROVED** [review]
Thanks for working together with me to make these changes! Yay to standardizing our spacing rules.

**Pull request merged**
