### PR TITLE
platform/jimfuqian/10508-Update-all-schemas-references-to-URIs

### PR DESCRIPTION
**Pull request by JFU-NAVA-PBC**
This PR:

Change all the schema reference from file path to URI
 
Test Steps:
1. Pass all tests

## Changes
- Going through all schema files (.yml), do the requested change: i.e. change any schema reference in path syntax to URI - e.g. - schema: classpath:/metadata/hl7_mapping/resources/Location/HD.yml
- Going through all kotlin sources, do the requested change to any schema references
- Copy metadata/hl7_mapping and metadata/fhir_transforms to src/main/resources/metadata to satisfy resource lookup in the URI based resources (schemas) resolution.

### Testing
- [X] Tested locally?
- [X] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

### CODE REVIEW

**Review by mkalish — CHANGES_REQUESTED** [review]
I think you might need to try this one more time?  The PR is showing that all the files are new and all the files in /metadata still exist.  Was this done with `git mv`? (will maintain the history)

**Comment by JFU-NAVA-PBC** [comment]
> I think you might need to try this one more time? The PR is showing that all the files are new and all the files in /metadata still exist. Was this done with `git mv`? (will maintain the history)

I still keep hl7_mapping and fhir_transforms under prime-route around, plan to remove it when everything good, but I can remove it now...

**Comment by JFU-NAVA-PBC** [comment]
> @JFU-NAVA-PBC It's less about the order and more about maintaining the git history for these files. Currently, this PR adds brand new files and deletes old ones. If I look at the git history all the files will say the got added this week.

I see, I agree that git mv would keep a cleaner history.
let me do that.

**Comment by JFU-NAVA-PBC** [comment]
Close this PR, it is replaced by PR 13103:

https://github.com/CDCgov/prime-reportstream/pull/13103

**Pull request closed without merging**
