### PR TITLE
1213 Add CSV to HL7 integration tests

### PR DESCRIPTION
**Pull request by carlosfelix2**
This PR adds an integration test for the conversion from CSV to HL7 to verify that the generation of HL7 data is not broken with changes to the baseline.  This works in the same manner as the HL7 to CSV tests (formerly known as the ObservationMessageTest), where you have a folder with CSV input data and a companion HL7 file with the expected HL7 output data.  The tests will generate errors and warnings as follows:
Errors are generated when:
1. The number of reports is different
2. A segment in the expected values does not exist in the actual values
3. A expected component value does not match the actual value

Warnings are generated when:
1. A component actual value exists, but no expected value.

Test steps:
1. Build the baseline with `./gradlew package`
2. Verify the test results for both the test and testIntegration test suite.  See build/reports/test.
3. You can run the integration test only with `./gradlew testIntegration` and force it with `./gradlew testIntegration -Pforcetest`

## Changes
- Create a new test suite called integration tests that runs separate from the unit tests.  We will be adding tests like quicktest to this suite
- Publish the test reports in Github Actions and the PR
- Created CSV to HL7 test 
- Renamed the old ObservationMessageTest to HL7 to CSV conversion tests.
- Increased the wait time for the DEV settings container, otherwise I could not run the router correctly
- Added extra check to DateTimeOffsetMapper as it was throwing an exception when a date field is empty

### Testing
- [x] Tested locally?
- [x] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Security
- [ ] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

### Process
- [x] Includes a summary of what a code reviewer should verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
- #1213

### CODE REVIEW

**Comment by MauriceReeves-usds** [comment]
@carlosfelix2 I linked this PR to #1213 for you.

**Comment by RickHawesUSDS** [comment]
Is it possible to make a gradle option to create take the current output and bless it as the new baseline? Or is that what PforceTest does?

**Comment by carlosfelix2** [comment]
> Is it possible to make a gradle option to create take the current output and bless it as the new baseline? Or is that what PforceTest does?

It is possible, but will need to add functionality to create those files.  I actually did just that, grabbed the current output then created the test files.  I'll add another issue for that.  forcetest is just to ignore the gradle up-to-date checks and run the test regardless of changes.

**Comment by carlosfelix2** [comment]
I have been thinking a bit more about this, and when we move the quicktest to this testIntegration suite I really do not want that to run as part of the package task.  Otherwise the local build will take too long.  It should run as a separate call to testIntegration and added as a new step in the Github Actions build.

**Comment by jimduff-usds** [comment]
> I have been thinking a bit more about this, and when we move the quicktest to this testIntegration suite I really do not want that to run as part of the package task. Otherwise the local build will take too long. It should run as a separate call to testIntegration and added as a new step in the Github Actions build.

The quickTest has become the slowTest.   It needs to be rewritten.    There's no reason to test all those states that use the same schema, and there are other useful tests (eg, from all the new Waters schemas, and hhsprotect) that are not in it.

**Comment by RickHawesUSDS** [comment]
The issue that I ran into with the ObservationMessageTests was when I tried to add a new element, all of the expected test files needed to be updated. Could the comparison be updated to accept new columns? I'm not sure if I actually believe this is a good idea, but its worth discussing.

**Comment by carlosfelix2** [comment]
> The issue that I ran into with the ObservationMessageTests was when I tried to add a new element, all of the expected test files needed to be updated. Could the comparison be updated to accept new columns? I'm not sure if I actually believe this is a good idea, but its worth discussing.

This was resolved by removing the one test for number of columns.  Adding a new field to a schema will not fail the test.

**Review by MauriceReeves-usds — APPROVED** [review]

**Pull request merged**
