### PR TITLE
Implemented parallel downloads in batch step

### PR DESCRIPTION
**Pull request by thetaurean**
This PR adds the use of coroutines in the batch step to facilitate parallel download and processing of report files.

Test Steps:

1. Set debug level logging in `src/main/resources/log4j2.xml` (line 31)
2. Run smoke tests on this feature branch
3. Observe logs for `Starting download for blobUrl` and corresponding `Finished` messages. You should see multiple downloads start in parallel.

## Changes
- BatchFunction.batchUniversalData() and WorkflowEngine.createHeader() now make use of `runBlocking`, `async`, and `awaitAll` to enable parallel download and processing of reportfiles.
- Added debug level logging for individual downloads; info level logging for aggregated duration of downloads

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] Added tests?

## Linked Issues
- Fixes #issue

## To Be Done
- Logging
- Test instructions (in this PR)

### CODE REVIEW

**Review by mkalish — COMMENTED** [review]
Changes look good, but I'm not quite sure how to test this?  The logging change in the test steps only exist in this branch.

I did run the smoketests with master and this branch, but there was not a difference in runtime (I assume limited number of downloads combined with not having to go over the wire).

Any thoughts on if we could send a message that would demonstrate this functionality?

**Review by mkalish — APPROVED** [review]
Changes look good to me!  Confirmed that I can see multiple downloads happening at the same time
```
[2023-09-15T12:20:29.299Z] 08:20:29.299 [pool-2-thread-24][47] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.CSV%2Faz-covid-19-3c4fef1d-75df-4c63-84aa-1918967c8a58-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.302Z] 08:20:29.302 [pool-2-thread-45][68] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH%2Faz-covid-19-hl7-03989875-04fa-4110-8c5f-6b91d8c7f497-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.305Z] 08:20:29.305 [pool-2-thread-5][28] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PPK%2Faz-covid-19-hl7-a3c23a48-c772-4b1f-aa6c-f10b8a71833a-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.307Z] 08:20:29.307 [pool-2-thread-47][70] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PEM%2Faz-covid-19-hl7-6d1493df-12a7-4451-a0dd-957031ad8979-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.312Z] 08:20:29.311 [pool-2-thread-17][40] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_LOCAL_TIME_CONVERT%2Fcovid-19-556609fb-fa45-4242-9af3-9ecb4997c09f-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.312Z] 08:20:29.311 [pool-2-thread-24][47] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Finished download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.CSV%2Faz-covid-19-3c4fef1d-75df-4c63-84aa-1918967c8a58-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.313Z] 08:20:29.313 [pool-2-thread-45][68] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Finished download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH%2Faz-covid-19-hl7-03989875-04fa-4110-8c5f-6b91d8c7f497-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.314Z] 08:20:29.313 [pool-2-thread-5][28] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Finished download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PPK%2Faz-covid-19-hl7-a3c23a48-c772-4b1f-aa6c-f10b8a71833a-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.314Z] 08:20:29.314 [pool-2-thread-47][70] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Finished download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PEM%2Faz-covid-19-hl7-6d1493df-12a7-4451-a0dd-957031ad8979-20230915081954.internal.csv - {}
[2023-09-15T12:20:29.316Z] 08:20:29.316 [pool-2-thread-24][47] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.CSV%2Faz-covid-19-5b7ef296-325f-4897-9eb2-db894a02f8d6-20230915081955.internal.csv - {}
[2023-09-15T12:20:29.318Z] 08:20:29.318 [pool-2-thread-45][68] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH%2Faz-covid-19-hl7-87e0a9ec-8690-4f12-98dd-3e118b6d9f86-20230915081955.internal.csv - {}
[2023-09-15T12:20:29.319Z] 08:20:29.319 [pool-2-thread-5][28] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PPK%2Faz-covid-19-hl7-926b59cc-bc9f-406f-823a-9cff8fc51ca3-20230915081955.internal.csv - {}
[2023-09-15T12:20:29.320Z] 08:20:29.320 [pool-2-thread-47][70] DEBUG gov.cdc.prime.router.azure.BlobAccess - BlobAccess Starting download for blobUrl http://localhost:10000/devstoreaccount1/reports/batch%2Fignore.HL7_BATCH_PEM%2Faz-covid-19-hl7-534fb4f7-00aa-4856-8ded-168d65ece05e-20230915081955.internal.csv - {}
```

**Comment by arnejduranovic** [comment]
@thetaurean please update PR description with ticket you are fixing

**Review by arnejduranovic — COMMENTED** [review]
This looks good to me, but the AC mentions refactoring. Were we not able to prevent the blobs from getting downloaded twice? `batchUniversalData` gets `validHeaders` passed in which should contain the downloaded blobs, but it downloads the blobs again?

**Comment by thetaurean** [comment]
After a quick huddle I suggested that we create a new bug ticket (#11370) to explicitly call out the double download bug.

This could have probably been kept in the same branch/PR but I also didn't want to further delay merging this since it can impact production.

**Pull request merged**
