### PR TITLE
Chain monorepo precommit to frontend precommit

### LINKED ISSUE #10903: Chain monorepo precommit to frontend precommit
Currently frontend's precommit scripting is handled solely in the monorepo's `.environment` files. For cleaner separation of concerns the frontend's precommit scripting should be contained within the frontend-react folder and chained to from `.environment`. Due to being contained in a monorepo, our precommit scripting must still only run tasks on changes to staged files in our area, so that we don't unnecessarily increase commit times to changes outside our folder or return false errors. Our yarn check script file should be moved somewhere within frontend-react where most appropriate.

Acceptance Criteria:
- [ ] frontend project updated to handle precommit tasks (including moved yarn check script)
- [ ] these tasks only run on staged file changes within frontend
- [ ] our precommit is called from `.environment` precommit

### PR DESCRIPTION
**Pull request by jpandersen87**
Fixes #10903

This PR:

- Sets up frontend-react project to handle precommit checks more in-depth
  - husky and lint-staged dev dependencies added and configured
  - staged files will be linted with auto-fixing enabled
  - staged files will also be tested
- Moves pre-existing checks from `.environment` to frontend
  - yarn lock script moved and updated
- Call frontend's precommit from `.environment`'s

### CODE REVIEW

**Review by penny-lischer — APPROVED** [review]
LGTM

**Review by snesm — CHANGES_REQUESTED** [review]
On Ubuntu `git commit -a`:

> frontend-react/.husky/pre-commit: 3: .: cannot open frontend-react/.husky/_/husky.sh: No such file

**Comment by jpandersen87** [comment]
> On Ubuntu `git commit -a`:
> 
> > frontend-react/.husky/pre-commit: 3: .: cannot open frontend-react/.husky/_/husky.sh: No such file

Thanks for mentioning this issue. Investigating why yarn isn't running the postinstall script.

**Comment by jpandersen87** [comment]
> On Ubuntu `git commit -a`:
> 
> > frontend-react/.husky/pre-commit: 3: .: cannot open frontend-react/.husky/_/husky.sh: No such file

I have now observed that yarn will not output any messages indicating failure when its process is killed by the OS kernel (in my situation, due to out-of-memory). After fixing the memory issue, and some ubuntu-specific scripting issues, I was able to successfully run the pre-commit scripting from a fresh repo pull after running yarn. Please retry this branch on your ubuntu instance with the latest changes (and checking its memory) and let me know your results.

**Review by snesm — APPROVED** [review]

**Pull request merged**
