### PR TITLE
Update to Node 18 #7078

### LINKED ISSUE #7078: Update to Node 18
## Problem statement

Node 16 LTS ends **September 11, 2023**. Our current node required version is `16.18.0`. We will need to update the app and CI to run on Node 18 by the end of Node 16 LTS.

## What you need to know

- [Node EOL (end of life)](https://endoflife.date/nodejs)
- Using NVM (Node version manager) that has some info you may need to know

## Acceptance criteria

- [ ] ReportStream's front end requires Node 18.x.x
- [ ] Github Actions frontend-build requires Node 18.x.x
- [ ] Update the .nvmrc

## To do

- [ ] ...

### PR DESCRIPTION
**Pull request by jpandersen87**
This PR updates the node version to the current LTS: 18.13.X. Closes #7078

### CODE REVIEW

**Review by snesm — APPROVED** [review]

**Comment by stephenkao** [comment]
@jpandersen87 Are you running into request proxy issues locally with this upgrade?

```
Proxy error: Could not proxy request /api/settings/organizations from localhost:3000 to http://localhost:7071.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

I just checked out to `master` to verify that it's not happening there 🤔 I'm going to look into the breaking changes to see if anything could potentially be related, but I just wanted to check with you beforehand!

**Comment by jpandersen87** [comment]
> @jpandersen87 Are you running into request proxy issues locally with this upgrade?
> 
> ```
> Proxy error: Could not proxy request /api/settings/organizations from localhost:3000 to http://localhost:7071.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
> ```
> 
> I just checked out to `master` to verify that it's not happening there 🤔 I'm going to look into the breaking changes to see if anything could potentially be related, but I just wanted to check with you beforehand!

I did not but will check again.

**Comment by jpandersen87** [comment]
Scratch that, when checking the submissions page after imitating simple_report I get the error. Investigating.

**Comment by jpandersen87** [comment]
Was an error on my end with the java app not running. Cannot reproduce proxy errors in dev. However, node 18 support seem to be incomplete for our dependency msw: https://github.com/mswjs/msw/issues/1388

**Comment by jpandersen87** [comment]
There's a hacky workaround mentioned here: https://github.com/mswjs/interceptors/pull/283#issuecomment-1333954204 but will not go down that road. We'll have to either wait for full node 18 support or change libraries, but for now this is blocked.

**Review by penny-lischer — APPROVED** [review]
LGTM

**Comment by stephenkao** [comment]
@jpandersen87 What do you think about closing this for now and reopening when the MSW issue is resolved?  Not a big deal, though -- just thinking about keeping the pull request list smaller!

**Comment by jpandersen87** [comment]
Closing for now

**Pull request closed without merging**
