### PR TITLE
Website Redesign - Refer health care organizations

### LINKED ISSUE #10913: Website Redesign - Refer health care organizations
As a User,
I want to visit the ReportStream **Refer health care organizations** Page,
So that I can become informed about how to inform other health care organizations about ReportStream

Designs
- Figma Link: https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design

Content Updates
- [See Figma Link](https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design)

Page Title
- "CDC ReportStream - Refer health care organizations" 

Analytics
- All links
- Page Load

Storybook updates
- TBD

Verification Steps
- Signed off in Staging by Product / Design
- Signed off in Production by Product / Design / Engineering

Acceptance Criteria:
- [ ] Analytics / Metrics Required 
- [ ] Storybook update required
- [ ] Unit Tests
- [ ] End to End Tests
- [ ] Manual Testing Steps

Dependencies:
- Designs - https://www.figma.com/file/Du7feM8huRDAAZCQcUIj93/Website-Redesign?type=design&node-id=1267-6590&mode=design
- Platform API Endpoints - N/A
- Links - TBD

Additional Details:
- The deployment strategy will follow the general deployment strategy for the Website Redesign EPIC. We will deliver this page in isolation from the other pages. 
- Conversion to MDX will be determined by the Engineer owning this ticket

### PR DESCRIPTION
**Pull request by jpandersen87**
Fixes #10913

This PR implements the refer healthcare organizations page.

### CODE REVIEW

**Review by etanb — APPROVED** [review]

**Comment by audreykwr** [comment]
- [ ] missing a comma after set up in the first sentence of body copy. Refer to figma if you need more details
- [ ] I think we can un-hyperlink and remove the external link icon on all references to reportstream@cdc.gov because they are not referenced for them to email it then.
- [ ] let us know should go to the contact form instead of mailto, link is in figma

**Comment by yudonoodles** [comment]
**Spacing notes:**

- [ ] Add margin-top and margin-bottom to usa-summary-box: 32px
- [ ] Add margin-top to H3: 32px (this should have already been updated if it was updated on the [Get started sending data page](https://github.com/CDCgov/prime-reportstream/pull/11020)
- [ ] Add margin-top on H2: 64px (as well as this one should also be updated)
- [ ] As a result of adding extra spacing of 64px, we no longer need hr tag on this page. Please remove all hr tags. 
- Noting here for future: will update the color of the summary box once we have the new color palette, for now the default teal for summary box is alright

**Comment by audreykwr** [comment]
The current staging environment misses one of the hyperlinks flagged in this point:

- [ ] I think we can un-hyperlink and remove the external link icon on all references to [reportstream@cdc.gov](mailto:reportstream@cdc.gov) because they are not referenced for them to email it then.

**Comment by jpandersen87** [comment]
> The current staging environment misses one of the hyperlinks flagged in this point:
> 
> * [ ]  I think we can un-hyperlink and remove the external link icon on all references to [reportstream@cdc.gov](mailto:reportstream@cdc.gov) because they are not referenced for them to email it then.

Can you be specific as to where this hyperlink is on trial 3?

**Review by yudonoodles — APPROVED** [review]

**Review by audreykwr — APPROVED** [review]

**Pull request merged**
